run_name: gliner_pii_run
backend: gliner
model: nvidia/gliner-PII
threshold: 0.5
label_map: config/ner_baseline/label_map.yaml
device: cuda
input_dataset: disi-unibo-nlp/paint-it-black
input_split: base
from_hub: true
output_dir: output/ner_baseline
wandb: false
