run_name: gliner_pii_large_run
backend: gliner
model: knowledgator/gliner-pii-large-v1.0
threshold: 0.3
label_map: config/ner_baseline/label_map.yaml
device: cuda
input_dataset: disi-unibo-nlp/paint-it-black
input_split: base
from_hub: true
output_dir: output/ner_baseline
wandb: false
